"""Training entry points and reusable MONAI orchestration helpers."""

from .train_kaggle import KaggleTrainingConfig, build_kaggle_monai_training_components, build_kaggle_training_run_name
from .kaggle_research import (
    KaggleResearchRunPaths,
    KaggleResearchTrainingError,
    ResearchKaggleDataConfig,
    ResearchKaggleTrainingConfig,
    ResearchKaggleTrainingResult,
    build_kaggle_run_paths,
    load_research_kaggle_training_config,
    run_research_kaggle_training,
)
from .train_oasis import (
    OASISRunResult,
    OASISTrainingConfig,
    build_oasis_monai_training_components,
    build_oasis_training_run_name,
    run_oasis_monai_training_epoch,
)
from .oasis_research import (
    CheckpointConfig,
    EarlyStoppingConfig,
    LossConfig,
    OptimizerConfig,
    ResearchDataConfig,
    ResearchOASISTrainingConfig,
    ResearchRunPaths,
    ResearchTrainingResult,
    SchedulerConfig,
    build_run_paths,
    load_research_oasis_training_config,
    run_research_oasis_training,
)
from .oasis_experiment import OASISExperimentConfig, OASISExperimentResult, run_oasis_experiment
from .experiment_tracking import (
    ExperimentTrackingConfig,
    ExperimentTrackingPaths,
    TrackedExperimentResult,
    export_tracked_oasis_experiment,
    load_experiment_rows,
)
from .model_selection import (
    ModelSelectionError,
    OASISModelSelectionConfig,
    OASISModelSelectionStudyResult,
    StudyMetricAggregate,
    build_seeded_experiment_config,
    run_oasis_model_selection_study,
)
from .trainer_utils import (
    MonaiTrainingComponents,
    TrainingArtifacts,
    build_monai_adam_optimizer,
    build_monai_classification_loss,
    build_monai_simple_inferer,
    build_training_artifacts,
)

__all__ = [
    "CheckpointConfig",
    "EarlyStoppingConfig",
    "ExperimentTrackingConfig",
    "ExperimentTrackingPaths",
    "KaggleTrainingConfig",
    "KaggleResearchRunPaths",
    "KaggleResearchTrainingError",
    "LossConfig",
    "ModelSelectionError",
    "MonaiTrainingComponents",
    "OASISRunResult",
    "OASISTrainingConfig",
    "OASISExperimentConfig",
    "OASISExperimentResult",
    "OASISModelSelectionConfig",
    "OASISModelSelectionStudyResult",
    "OptimizerConfig",
    "ResearchDataConfig",
    "ResearchKaggleDataConfig",
    "ResearchKaggleTrainingConfig",
    "ResearchKaggleTrainingResult",
    "ResearchOASISTrainingConfig",
    "ResearchRunPaths",
    "ResearchTrainingResult",
    "SchedulerConfig",
    "StudyMetricAggregate",
    "TrackedExperimentResult",
    "build_run_paths",
    "TrainingArtifacts",
    "build_seeded_experiment_config",
    "build_kaggle_monai_training_components",
    "build_kaggle_training_run_name",
    "build_monai_adam_optimizer",
    "build_monai_classification_loss",
    "build_monai_simple_inferer",
    "build_oasis_monai_training_components",
    "build_oasis_training_run_name",
    "build_training_artifacts",
    "build_kaggle_run_paths",
    "load_research_kaggle_training_config",
    "load_research_oasis_training_config",
    "load_experiment_rows",
    "export_tracked_oasis_experiment",
    "run_research_kaggle_training",
    "run_research_oasis_training",
    "run_oasis_model_selection_study",
    "run_oasis_monai_training_epoch",
    "run_oasis_experiment",
]
