"""Clinical workflow schemas for nurse/care-team dashboards."""

from __future__ import annotations

from datetime import date, datetime
from enum import Enum
from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field, field_validator

from .common import AuditFields, DataProvenance


class MedicationStatus(str, Enum):
    """Medication lifecycle status."""

    active = "active"
    paused = "paused"
    discontinued = "discontinued"
    completed = "completed"


class AppointmentStatus(str, Enum):
    """Appointment workflow status."""

    scheduled = "scheduled"
    completed = "completed"
    canceled = "canceled"
    no_show = "no_show"


class AlertPriority(str, Enum):
    """Care-team alert priority."""

    low = "low"
    moderate = "moderate"
    high = "high"
    urgent = "urgent"


class AlertStatus(str, Enum):
    """Care-team alert resolution state."""

    open = "open"
    acknowledged = "acknowledged"
    resolved = "resolved"
    dismissed = "dismissed"


class CognitiveTestScore(BaseModel):
    """Cognitive assessment score tied to a patient and optional scan session."""

    model_config = ConfigDict(extra="forbid")

    cognitive_score_id: UUID = Field(default_factory=uuid4)
    patient_id: UUID
    test_name: str = Field(description="Examples: MMSE, MoCA, CDR.")
    score: float
    max_score: float | None = None
    interpretation: str | None = None
    administered_at: datetime | None = None
    administered_by: UUID | None = None
    related_scan_id: UUID | None = None
    provenance: DataProvenance = Field(default_factory=DataProvenance)
    audit: AuditFields = Field(default_factory=AuditFields)
    metadata: dict[str, Any] = Field(default_factory=dict)


class MedicationRecord(BaseModel):
    """Medication entry for patient-management workflows."""

    model_config = ConfigDict(extra="forbid")

    medication_id: UUID = Field(default_factory=uuid4)
    patient_id: UUID
    medication_name: str
    dose: str | None = None
    route: str | None = None
    frequency: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    prescribing_clinician_id: UUID | None = None
    status: MedicationStatus = MedicationStatus.active
    indication: str | None = None
    audit: AuditFields = Field(default_factory=AuditFields)
    metadata: dict[str, Any] = Field(default_factory=dict)


class AppointmentRecord(BaseModel):
    """Appointment record for future scheduling/dashboard features."""

    model_config = ConfigDict(extra="forbid")

    appointment_id: UUID = Field(default_factory=uuid4)
    patient_id: UUID
    scheduled_start: datetime
    scheduled_end: datetime | None = None
    appointment_type: str
    location: str | None = None
    assigned_clinician_id: UUID | None = None
    status: AppointmentStatus = AppointmentStatus.scheduled
    related_scan_id: UUID | None = None
    notes: str | None = None
    audit: AuditFields = Field(default_factory=AuditFields)
    metadata: dict[str, Any] = Field(default_factory=dict)


class CaregiverNote(BaseModel):
    """Caregiver or care-team narrative note."""

    model_config = ConfigDict(extra="forbid")

    note_id: UUID = Field(default_factory=uuid4)
    patient_id: UUID
    author_id: UUID | None = None
    author_role: str | None = Field(default=None, description="Examples: caregiver, nurse, clinician.")
    note_text: str
    observed_at: datetime | None = None
    tags: list[str] = Field(default_factory=list)
    is_sensitive: bool = True
    audit: AuditFields = Field(default_factory=AuditFields)
    metadata: dict[str, Any] = Field(default_factory=dict)


class SymptomLog(BaseModel):
    """Structured symptom log for dashboard trend display."""

    model_config = ConfigDict(extra="forbid")

    symptom_log_id: UUID = Field(default_factory=uuid4)
    patient_id: UUID
    symptom_name: str
    severity: int = Field(ge=0, le=10)
    observed_at: datetime
    reported_by_id: UUID | None = None
    reported_by_role: str | None = None
    notes: str | None = None
    audit: AuditFields = Field(default_factory=AuditFields)
    metadata: dict[str, Any] = Field(default_factory=dict)


class AlertRecord(BaseModel):
    """Care-team alert generated by users, rules, or model/longitudinal outputs."""

    model_config = ConfigDict(extra="forbid")

    alert_id: UUID = Field(default_factory=uuid4)
    patient_id: UUID
    alert_type: str
    priority: AlertPriority = AlertPriority.moderate
    status: AlertStatus = AlertStatus.open
    title: str
    message: str
    generated_at: datetime
    generated_by: str = Field(description="Examples: nurse, clinician, longitudinal_engine, model_inference.")
    related_scan_id: UUID | None = None
    related_report_uri: str | None = None
    acknowledged_by: UUID | None = None
    acknowledged_at: datetime | None = None
    resolved_by: UUID | None = None
    resolved_at: datetime | None = None
    audit: AuditFields = Field(default_factory=AuditFields)
    metadata: dict[str, Any] = Field(default_factory=dict)

    @field_validator("message")
    @classmethod
    def _avoid_diagnosis_language(cls, value: str) -> str:
        """Keep generated alerts compatible with decision-support wording."""

        lowered = value.lower()
        forbidden = ("diagnosed with", "has alzheimer")
        if any(term in lowered for term in forbidden):
            raise ValueError("Alert message must avoid diagnosis claims.")
        return value

